labels:
  - name: pending triage
    color: 9e9e9e
    description: Awaiting initial triage

  - name: dependencies
    color: 0366d6
    description: Dependency updates

  - name: bug
    color: d73a4a
    description: Something isn't working

  - name: enhancement
    color: a2eeef
    description: New feature or request

  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation

  - name: chore
    color: cccccc
    description: Build, tooling, or repository chores

  - name: good first issue
    color: 7057ff
    description: Suitable for first-time contributors

  - name: help wanted
    color: 008672
    description: Extra attention is needed

  - name: question
    color: d876e3
    description: Further information is requested

  - name: performance
    color: fbca04
    description: Performance-related improvements

  - name: security
    color: b60205
    description: Security-related changes or reports

  - name: duplicate
    color: cfd3d7
    description: This issue or PR already exists

  - name: invalid
    color: e4e669
    description: This doesn't seem right

  - name: wontfix
    color: ffffff
    description: This will not be worked on
