name: "🐞 Bug report"
description: Report a reproducible bug in @sigrea/core
labels: ["pending triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please provide a minimal reproduction and enough context to understand the issue.
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Node version, package manager, OS, @sigrea/core version
      placeholder: "Node 20.x, pnpm 10.x, macOS 14, @sigrea/core 0.1.x"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Minimal reproduction
      description: Link to a minimal repo or code snippet that reproduces the issue
      placeholder: "Link to repo / gist / steps"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened? Include error messages/logs.
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Validations
      options:
        - label: I have read CONTRIBUTING.md and CODE_OF_CONDUCT.md
          required: true
        - label: I searched existing issues and did not find a duplicate
          required: true

