name: "🚀 Feature request"
description: Propose an improvement or new capability
labels: ["pending triage"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the problem and the proposed solution. Include alternatives considered and use cases.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: API shape, behavior, and examples
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Other approaches you have considered
  - type: checkboxes
    id: checks
    attributes:
      label: Validations
      options:
        - label: I have read CONTRIBUTING.md and CODE_OF_CONDUCT.md
          required: true
        - label: I searched existing discussions/issues to avoid duplicates
          required: true

