name: compressed-size
on:
  push:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
concurrency: size-${{ github.ref }}
jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: './dist/**/*.{js,mjs}'
          exclude: |
            **/*.map
            **/*.d.ts
