name: lint-workflows
on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/*.yml"
  push:
    paths:
      - ".github/workflows/**"
      - ".github/*.yml"
permissions:
  contents: read
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/actionlint@7de1cc49de6e05d981ddc7d58a34a99e8d5b0950
