name: lint-workflows
on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/*.yml"
  push:
    paths:
      - ".github/workflows/**"
      - ".github/*.yml"
permissions:
  contents: read
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/actionlint@018b92b41f5aea95e7b721c447f9328cb2127937
