name: lint-workflows
on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/*.yml"
  push:
    paths:
      - ".github/workflows/**"
      - ".github/*.yml"
permissions:
  contents: read
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/actionlint@af317a90dd6c569d9d6196a6eca3546e3a17bf7a
