name: semantic-pr
on:
  pull_request_target:
    types: [opened, edited, synchronize]
permissions: {}
jobs:
  lint:
    permissions:
      contents: read
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            chore
            docs
            test
            refactor
            ci
            build
            perf
            style
            revert
